### ISSUE TITLE
How to use this project

### ISSUE THREAD

**Issue by hendisantika** [yeghishe/minimal-scala-akka-http-seed#2]
Nice repo.

But How to use this project?
```
sbt run
 ```
or what? and what is the result?
Thanks

**Comment by yeghishe** [comment]
@hendisantika are you familiar with activator? This is an activator template.... the purpose is to generate akka-http projects.

* [Activator](http://www.lightbend.com/community/core-tools/activator-and-sbt)
* `activator new <YOUR PROJECT NAME> minimal-scala-akka-http-seed`

Let me know if there is more I can help with.

**Comment by mslinn** [comment]
Instead of using the template to make a new Activator/SBT project, I tried to run the project as is. When I type:

```
$ sbt run
[info] Loading global plugins from /home/mslinn/.sbt/0.13/plugins
[info] Loading project definition from /var/work/experiments/akka/minimal-scala-akka-http-seed/project
[info] Updating {file:/var/work/experiments/akka/minimal-scala-akka-http-seed/project/}minimal-scala-akka-http-seed-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to minimal-scala-akka-http-seed (in build file:/var/work/experiments/akka/minimal-scala-akka-http-seed/)
[info] Updating {file:/var/work/experiments/akka/minimal-scala-akka-http-seed/}root...
[info] Resolving jline#jline;2.14.1 ...
[info] Done updating.
[info] Compiling 4 Scala sources to /var/work/experiments/akka/minimal-scala-akka-http-seed/target/scala-2.12/classes...
[info] Running io.github.yeghishe.Main 
[DEBUG] [03/03/2017 14:21:39.183] [run-main-0] [EventStream(akka://default)] logger log1-Logging$DefaultLogger started
[DEBUG] [03/03/2017 14:21:39.184] [run-main-0] [EventStream(akka://default)] Default Loggers started
[DEBUG] [03/03/2017 14:21:39.434] [run-main-0] [AkkaSSLConfig(akka://default)] Initializing AkkaSSLConfig extension...
[DEBUG] [03/03/2017 14:21:39.437] [run-main-0] [AkkaSSLConfig(akka://default)] buildHostnameVerifier: created hostname verifier: com.typesafe.sslconfig.ssl.DefaultHostnameVerifier@eb21868
[DEBUG] [03/03/2017 14:21:39.919] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] Successfully bound to /0:0:0:0:0:0:0:0:9000
```

Now when I browse to `localhost:9000` or `localhost:9000/status`, I get `The requested resource could not be found.` .... even though the console shows:

```
[DEBUG] [03/03/2017 14:22:00.521] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
```

This is true on Ubuntu and Windows. Running with Activator instead of SBT gives the same result, of course.

**Comment by yeghishe** [comment]
You're right @mslinn, and the reason is because recently I introduced version endpoints and it uses v1 when you generate from the template.
If you execute `GET /v1/status` it should work. Also if you can point out where I have /status documented I'll make sure to get it updated also

**Comment by mslinn** [comment]
So the question of how to use this project remains unanswered. What is the endpoint for the current version?

**Comment by yeghishe** [comment]
The project is intended to be used as an activator template to generate akka http projects.
From the command line, you can execute `activator new <YOUR PROJECT NAME> minimal-scala-akka-http-seed` to generate a project. From activator UI fine the template named `minimal-scala-akka-http-seed` and generate the project.

Once the project is generated you get few things out of the box:
* Most of the wiring is done in Main. Create new endpoints and add them to [this map](https://github.com/yeghishe/minimal-scala-akka-http-seed/blob/master/src/main/scala/io/github/yeghishe/Main.scala#L23), it will do the rest of wiring for you (`status` "path" in the map will become `/v1/status` endpoint). Think of those key-value mappings as /status is the prefix for all status routes, and there is a base prefix /v1.
* [Config](https://github.com/yeghishe/minimal-scala-akka-http-seed/blob/master/src/main/scala/io/github/yeghishe/Config.scala) is handled using ficus. Make sure to create your case classes for new config values you add in typesafe config. You can later mix in `Config` trait or import your values from `Config` object
* circe for json encode/decode 
* The project comes with cats library also now
* [StatusService](https://github.com/yeghishe/minimal-scala-akka-http-seed/blob/master/src/main/scala/io/github/yeghishe/StatusService.scala) which is more of a health check endpoint but the real goal is to act as a demo service. You'll be spending most of your time creating services and wiring those in Main file, into allRoutes file.
* [package](https://github.com/yeghishe/minimal-scala-akka-http-seed/blob/master/src/main/scala/io/github/yeghishe/package.scala) objects contains base classes so you don't have to repeat yourself for every service you create.
* The project uses ScalaTest. Extend from [ServiceTestBase](https://github.com/yeghishe/minimal-scala-akka-http-seed/blob/master/src/test/scala/io/github/yeghishe/ServiceTestBase.scala) for your route tests. See [StatusServiceTest](https://github.com/yeghishe/minimal-scala-akka-http-seed/blob/master/src/test/scala/io/github/yeghishe/StatusServiceTest.scala) as an example.
* Scalafmt for code formatting 
* Scala style for code style checking 
* Scoverate for code coverage 
* Revolve for local development
* Sbt native packager for packaging and deployment

**Comment by yeghishe** [comment]
@mslinn let me know if above helps/is enough. I'll put in in readme also.

**Comment by mslinn** [comment]
Much better, thanks. I think most people will try to run the project before using it as a basis for their projects. You might want to point out what they should notice when running the project unchanged.

**Comment by yeghishe** [comment]
@mslinn running the project as is also should work, although again it's purpose is to generate projects using activator.

How did you come across the repo if you don't mind me asking?

**Comment by mslinn** [comment]
This is how I look for interesting Activator projects:
```
$ activator list-templates | grep akka-http | grep seed
  akka-http-java-seed
  minimal-scala-akka-http-seed
```

**Comment by yeghishe** [comment]
Got it. thanks for the input @mslinn
